Rozwiązania zadań
graag/practicepython_go pull request #1
Opened 2018-10-08 23:10 UTC by gab-oss

7 i 10 są w jednym

2018-10-15 20:09 UTC, graag requested changes
Dzięki za rozwiązania. Są dobre.

Część wymaga niedużych poprawek.

Myślę że bardziej zaawansowane konstrukcje python przećwiczymy już na właściwym kodzie.

2018-10-15 20:09 UTC, graag commented on .vscode/settings.json
> +{
Dodajmy do projektu plik .gitignore - https://git-scm.com/docs/gitignore

Dodajmy do tego pliku .vscode tak żeby repozytorium git nie zawierało lokalnych ustawień środowiska vscode

Sam plik .vscode/settings.json do usunięcia z repozytorium git

2018-10-15 20:09 UTC, graag commented on character_input.py
> +age = int(input("Podaj wiek: "))
Dodajmy obsługę błędów - `try expect` na przypadek gdy użytkownik nie poda liczby.

2018-10-15 20:09 UTC, graag commented on check_primality_functions.py
> +check_primality(int(input("Podaj liczbe: ")))
Obsługa błędów

2018-10-15 20:09 UTC, graag commented on check_primality_functions.py
> +        print("{} to nie liczba pierwsza")
Nie brakuje przypadkiem `.format`?

2018-10-15 20:09 UTC, graag commented on check_primality_functions.py
> +    div = [elem for elem in range(2,num) if num%elem == 0]
Czy range musi przebiegać aż do `num`?
Czy musimy w każdym przypadku przechodzić całą pętlę?
Zaproponuj może rozwiązanie bez "list comprehension" które zwraca True albo False

2018-10-15 20:09 UTC, graag commented on divisors.py
> +num = int(input("Podaj liczbe: "))
Obsługa błędów

2018-10-15 20:09 UTC, graag commented on fibonacci.py
> +f = fibonacci(int(input("Podaj dlugosc sekwencji: ")))
Obsługa błędów

2018-10-15 20:09 UTC, graag commented on guessing_game_one.py
> +            inp = int(inp)
Obsługa błędów. W przypadku gdy podano nie liczbę zapytaj ponownie ...

2018-10-15 20:09 UTC, graag commented on list_comprehensions.py
> +a = [i**2 for i in range(10)]
Rozszerzmy zadanie o czytanie listy `a` z pliku.

Wykorzystaj moduł argparse https://docs.python.org/3/library/argparse.html aby pobrać nazwę pliku jako parametr.

Wykorzystaj moduł `json` oraz konstrukcję `with open` aby przeczytać listę z pliku w formacie JSON: https://www.json.org/

2018-10-15 20:09 UTC, graag commented on list_ends.py
> +    return e
Można też tak:
```
return l[0], l[-1]
```

A potem:
```
start, end = ends(l)
print(start)
print(end)
```

2018-10-15 20:09 UTC, graag commented on list_ends.py
> +l = generate(random.randrange(1, max_length))
Zamiast funkcji generate zaproponuj użycie: https://docs.python.org/3/library/random.html#random.sample

2018-10-15 20:09 UTC, graag commented on list_less_than_ten.py
> +num = int(input("Podaj liczbe: "))
Obsługa błędów

2018-10-15 20:09 UTC, graag commented on list_overlap.py
> +overlap = set([element for element in a if element in b])
Zaproponuj drugie rozwiązanie z wykorzystaniem dwóch set-ów zamiast 'list comprehension'

2018-10-15 20:09 UTC, graag commented on list_remove_duplicates.py
> +            r.append(elem)
Jak mógłby wyglądać ten algorytm żeby w każdym kroku pętli nie trzeba było przeszukiwać ponownie listy?? Bez użycia set-ów ...

2018-10-15 20:09 UTC, graag commented on odd_or_even.py
> +num = int(input("Podaj liczbe: "))
Obsługa błędów

2018-10-15 20:09 UTC, graag commented on list_remove_duplicates_set.py
> +import random
Dodaj możliwość wczytania listy z pliku.

Przy pomocy argparse obsłuż możliwość podania parametrów max_length, elem_range lub nazwy pliku z listą.

Plik z listą w formacie JSON

2018-10-15 20:09 UTC, graag commented on password_generator.py
> +ascii_max = 126
A jednak ktoś wie czym jest tablica ASCII :-)

2018-10-15 20:09 UTC, graag commented on password_generator.py
> +                if len(word) > 5:
Co będzie jeśli len(word)<=5 ???

2018-10-15 20:09 UTC, graag commented on password_generator.py
> +        line = file.readline()
Dla małego pliku bardziej opłaca się użyć `readlines()`. Dostaniesz od razu listę linii. Pod spodem python przeczyta i tak kawałek pliku do rozmiaru bufora zanim zacznie go dzielić na linie. Np: w moim przypadku:
```
>>> io.DEFAULT_BUFFER_SIZE
8192
```

2018-10-15 20:09 UTC, graag commented on reverse_word_order.py
> +    result = " ".join([spl[-1-i] for i in range(len(spl))])
Albo: `result = spl[::-1]`

2018-10-15 20:09 UTC, graag commented on reverse_word_order.py
> +    result = " ".join([spl[-1-i] for i in range(len(spl))])
https://www.pythoncentral.io/how-to-slice-listsarrays-and-tuples-in-python/

2018-10-15 20:09 UTC, graag commented on rock_paper_scissors.py
> +    if (dict.get(play1) + 1)%3 == dict.get(play2):
Powinno zadziałać `d[play1]` jeśli nie działało to możliwe że przez tego `dict-a`

2018-10-15 20:09 UTC, graag commented on rock_paper_scissors.py
> +dict = {"kamien": 0, "papier": 1, "nozyce": 2}
`dict` jest słowem zastrzeżonym w python. Zmień na coś innego

2018-10-15 20:09 UTC, graag commented on weak_password
> +Eärendil was a mariner
:-D

2018-10-15 20:09 UTC, graag commented on cows_and_bulls.py
> +        elif not inp.isdigit() or int(inp) < 1000 or int(inp) > 10000:
```
Podaj czterocyfrowa liczbe ('x', zeby zakonczyc): 4
Traceback (most recent call last):
  File "cows_and_bulls.py", line 36, in <module>
    game()
  File "cows_and_bulls.py", line 23, in game
    elif not inp.isdigit() or int(inp) < 1000 or int(inp) > 10000:
AttributeError: 'int' object has no attribute 'isdigit'
```

2018-10-15 20:09 UTC, graag commented on cows_and_bulls.py
> +        if spl1[i] == spl2[i]:
```
$ python3 cows_and_bulls.py
1234
Podaj czterocyfrowa liczbe ('x', zeby zakonczyc): 4444
Traceback (most recent call last):
  File "cows_and_bulls.py", line 37, in <module>
    game()
  File "cows_and_bulls.py", line 27, in game
    result = compare(inp, num)
  File "cows_and_bulls.py", line 7, in compare
    if spl1[i] == spl2[i]:
TypeError: 'int' object is not subscriptable
```

2018-10-15 20:09 UTC, graag commented on cows_and_bulls.py
> +            bulls = bulls + 1
Niech num = 1234, inp = 4444
Twój kod zwróci 1 cow i 3 bulls. Zaproponuj rozwiązanie które zwróci 1 cow, 0 bulls. Czyli takie porównywanie bez zwracania ...

2018-12-04 23:05 UTC, gab-oss commented
Dodałam poprawki. Przepraszam, że dopiero teraz

2019-02-13 10:35 UTC, graag requested changes
Świetna robota dzięki.

Znalazłem jeszcze kilka małych rzeczy do poprawy. Powinno Ci zająć chwilkę.

2019-02-13 10:35 UTC, graag commented on cows_and_bulls.py
> +            bulls = bulls + 1
Prawie dobrze:
```
1577
Podaj czterocyfrowa liczbe (0, zeby zakonczyc): 7111
0 cows, 2 bulls
Podaj czterocyfrowa liczbe (0, zeby zakonczyc): 6676
1 cows, 1 bulls
```

Oznaczasz jako "zużyte"  elementy spl2. Należałoby też oznaczyć jako zużyte elemety spl1 ...

2019-02-13 10:35 UTC, graag commented on list_comprehensions_json.py
> +parser.add_argument('jsonfile')
Rozwiązanie jest poprawne i masz rację że zazwyczaj taki plik przekażemy jako argument pozycyjny.

Oprócz argumentów pozycyjnych mogą występować argumenty nazwane (np: -h, --help) w formie długiej i/lub krótkiej. Takie argumenty zazwyczaj są opcjonalne.

Spróbujmy przedefiniować tą implementację tak by przyjmowała formę `-f|--file nazwa_pliku.json`. Oraz wymusić że nazwa musi być zawsze zdefiniowana:

- https://docs.python.org/3/library/argparse.html#name-or-flags
- https://docs.python.org/3/library/argparse.html#required
Dodaj jeszcze help text:
- https://docs.python.org/3/library/argparse.html#help

2019-02-13 10:35 UTC, graag commented on list_comprehensions_json.py
> +    a = data["a"]
Json nie musi być słownikiem. Może mieć po prostu postać listy:

```
cat input.json
[1,2,3,4,5]
```

Wtedy możesz bezpośrednio pracować na data ...

2019-02-13 10:35 UTC, graag commented on list_ends.py
> +        l = random.sample(range(len), n)
Mała uwaga ...

Twoja funkcja generate losuje próbkę z zwracaniem.

Żeby to samo uzyskać bezpośrednio z pakietu random zamiast random.sample można użyć random.choices

2019-02-13 10:35 UTC, graag commented on list_remove_duplicates.py
> +
Nice :)

2019-02-13 10:35 UTC, graag commented on list_remove_duplicates_set.py
> +if len(sys.argv) == 3:
:-D

Prawie dobrze.

Korzystasz z argparse więc nie ma powodu patrzyć na sys.argv

Wszystkie trzy parametry (-m, -r, -f) są opcjonalne więc jeśli któregoś zabraknie argparse nie rzuci błędem.

Wystarczy nadać im priorytet. Jeśli jest zdefiniowane args.f przyjmijmy że użytkownik chce użyc pliku. Jeśli nie używamy argumentów m i r.

Przy okazji jednoliterowe nazwy zmiennych są złą praktyką. Można tutaj temu zaradzić albo definiując argument dest przy wywołaniu funkcji add_argument. Albo definiując długą formę argumentu: `parser.add_argument('-m', '--max', type=int, help='-m=[max_length]')`

Wtedy będziesz miała: `args.max`

2019-02-19 10:19 UTC, graag approved these changes
Super

2019-02-19 10:19 UTC, merged